app = "j-royal-rumble"
primary_region = "sjc"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 120

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
